### ISSUE TITLE
DateTime conversion Exception

### ISSUE THREAD

**Issue by Macavirus** [jorinvo/letsdo.events#35]
Current deployed version at letsdo.events dumps the following when clicking on "Conference Activities" from the homepage:

 ```
clojure.lang.ExceptionInfo: Conversion failed {:path [[#object[java_time.graph.Types 0x3a4a99ef "[java.lang.String java.time.LocalDateTime]"] #object[java_time.graph.Types 0x6049d7bd "[java.time.LocalDate java.time.LocalDateTime]"]] [#object[java_time.graph.Types 0x7ac1b135 "[java.time.LocalDate java.time.LocalDateTime]"] #object[java_time.graph.Types 0x6a9c5c6a "[java.time.Duration]"]]], :arguments ["2019-05-24T19:00" #object[java.time.LocalDateTime 0x13dd1c11 "2020-01-05T15:57:13.714048"]], :to java.time.Duration}
	at java_time.amount$duration$fn__31694.invoke(amount.clj:50)
	at java_time.amount$duration.invokeStatic(amount.clj:50)
	at java_time.amount$duration.invoke(amount.clj:50)
	at lde.core.event$sort_by_upcoming$fn__33535.invoke(event.clj:175)
	at clojure.core$map$fn__5866.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.length(RT.java:1784)
	at clojure.lang.RT.seqToArray(RT.java:1725)
	at clojure.lang.LazySeq.toArray(LazySeq.java:132)
	at clojure.lang.RT.toArray(RT.java:1698)
	at clojure.core$to_array.invokeStatic(core.clj:344)
	at clojure.core$sort.invokeStatic(core.clj:3113)
	at clojure.core$sort_by.invokeStatic(core.clj:3119)
	at clojure.core$sort_by.invokeStatic(core.clj:3119)
	at clojure.core$sort_by.invoke(core.clj:3119)
	at lde.core.event$sort_by_upcoming.invokeStatic(event.clj:178)
	at lde.core.event$sort_by_upcoming.invoke(event.clj:167)
	at lde.core.event$upcoming_by_topic.invokeStatic(event.clj:185)
	at lde.core.event$upcoming_by_topic.invoke(event.clj:181)
	at lde.web.pages.topic$overview.invokeStatic(topic.clj:118)
	at lde.web.pages.topic$overview.invoke(topic.clj:110)
	at lde.web.middleware$authorize_topic_read$fn__34245.invoke(middleware.clj:21)
	at lde.web.middleware$load_topic$fn__34265.invoke(middleware.clj:46)
	at reitit.ring.coercion$fn__21967$fn__21969$fn__21970.invoke(coercion.cljc:34)
	at reitit.ring.coercion$fn__21990$fn__21992$fn__21993.invoke(coercion.cljc:66)
	at reitit.ring$ring_handler$fn__19602.invoke(ring.cljc:288)
	at lde.web$make_context_middleware$fn__38421$fn__38422.invoke(web.clj:194)
	at ring.middleware.session$wrap_session$fn__23496.invoke(session.clj:108)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__22397.invoke(keyword_params.clj:53)
	at ring.middleware.params$wrap_params$fn__22190.invoke(params.clj:67)
	at clj_honeycomb.middleware.ring$with_honeycomb_event$fn__38298$fn__38299.invoke(ring.clj:201)
	at clj_honeycomb.core$with_event_fn.invokeStatic(core.clj:479)
	at clj_honeycomb.core$with_event_fn.invoke(core.clj:465)
	at clojure.lang.Var.invoke(Var.java:393)
	at clj_honeycomb.middleware.ring$with_honeycomb_event$fn__38298.invoke(ring.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at aleph.http.server$handle_request$fn__15729$f__813__auto____15730.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__695$f__696.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.time.format.DateTimeParseException: Text '2019-05-24T19:00' could not be parsed, unparsed text found at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
	at java.base/java.time.LocalDate.parse(Unknown Source)
	at java.base/java.time.LocalDate.parse(Unknown Source)
	at java_time.local$eval31530$fn__31531.invoke(local.clj:111)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at java_time.defconversion$combinations$iter__30773__30777$fn__30778$fn__30779$fn__30780.doInvoke(defconversion.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at java_time.defconversion$wrap_validation$fn__30770.invoke(defconversion.clj:21)
	at java_time.graph$index_conversions$fn__30692.invoke(graph.clj:216)
	at java_time.graph$convert_via$fn__30757$fn__30758.invoke(graph.clj:310)
	at clojure.lang.PersistentUnrolledVector$Card2.reduce(PersistentUnrolledVector.java:478)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at java_time.graph$convert_via$fn__30757.invoke(graph.clj:310)
	... 47 more
```

**Comment by jorinvo** [comment]
Thanks :) Should be fixed now with https://github.com/jorinvo/letsdo.events/commit/74e3f20735ec8d6c7ecf4e41b431578e994d59bd.
